- project:
    templates:
      - openstack-python3-jobs-neutron
      - openstack-cover-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    vars:
      rtd_webhook_id: '224878'
    check:
      jobs:
        - openstack-tox-functional-with-sudo
        - ovn-bgp-agent-tempest-plugin:
            voting: false
    experimental:
      jobs:
        - openstack-tox-py310-with-oslo-master
    periodic-weekly:
      jobs:
        - openstack-tox-py310
        - openstack-tox-py310-with-oslo-master
